import type { Metadata } from 'next/types';

export async function generateMetadata({
    params,
}: {
    params: { category: string };
}): Promise<Metadata> {
    const { category } = await params;

    return {
        title: `Categoria`,
        description: 'Generated by create next app',
    };
}

export default function CategoryLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            {children}
        </>
    );
}
